const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const passportLocalMongoose = require("passport-local-mongoose").default;

// user name and password willbe generated by passport local mongoose so dont neeed to mention it in  our schema 
const userSchema = new Schema({
    email: {
        type: String,
        required: true
    }
});
// we used passportmongoose as plugin here becase it will automatically generate or implement username, hashing, salting and hashpassword 
userSchema.plugin(passportLocalMongoose);
module.exports = mongoose.model("User", userSchema);